name: CI-CD

on :
  push: 
     branches: ["feature/jaydeep"]
jobs: 
 build:
   runs-on: ubuntu-latest
   environment: EC2 
   
   steps:
      - name : checkout code
        uses: actions/checkout@v4

      - name : on push console:= console form action
        run : echo "Hello this is form action ${{ vars.EC2_HOST }}"
        
      - name : start ec2 deployment
        run : echo "start ec2 deployment ${{ vars.EC2_USER }}"
        
      - name : Deploy to EC2
        uses:  appleboy/ssh-action@v0.1.9

        with:
          host: 13.60.41.170
          username: ${{ vars.EC2_USER }}
          key: ${{ vars.EC2_KEY }}
          port: 22
          script: |
           cd /var/www/myapp/cicd/cicd
           git reset --hard git
           pull origin feature/jaydeep
           npm install 
           npm run build
           pm2 restart 0
           pm2 save
