name: CI-CD

on :
  push: 
     branches: ["feature/jaydeep"]
jobs: 
 build:
   runs-on: ubuntu-latest
   environment: Configure EC2 
   
   steps:
      - name : checkout code
        uses: actions/checkout@v4

      - name : on push console:= console form action
        run : echo "Hello this is form action"
        
      - name : start ec2 deployment
        run : echo "start ec2 deployment"
        
      - name : Deploy to EC2
        uses:  appleboy/ssh-action@v0.1.9

        with:
          host: 13.60.41.170
          username: ${{ secrets.EC2_USER }}
          key: MIIEowIBAAKCAQEA4/zwRsnm46RxfmWWLvjcVvZfzhFZ6vxB7vRkXyI13hawjcN1jxfjwnTZOUDASkwFgfUmxvAFHMx9R2RopAi3AsPeSn6bA1E2xvKe8D6outzaBf94Cwg8p0bT7ZX9QpwhZVpeRZg4sGI9uRhR4J4r36edjO3IlbxN4oTTiOE0Ebc8yyzTvOyvtLsJGMyseAflsf031uXEJR66+THo+n1I6Jk7ADokmwA/JfP2BQgoPR+AGd9M2+ALbCoawtEIO80aKOlBWk/Q+9Pt1v+g4VYSN8aBJ6Qge8u9XdQLxusdnFRv3JYo0Zp28WkXBo9TDDRxvYmzHH41RKBLtprJ9isHNwIDAQABAoIBADxlF/2YpKpvOIWEQbmlwTDkSVLcc9Z1Br5XTXOKK3zuw8x6F91VNcegjp7FEWtdIiRgHeqbUK9lWFaeOb4idOCtpGhVi5jgXcNsKEB6SNZfhP4Lw/AgOXkSoTeSASoxFAO2YbzL61CGZdVvpNj87aBs1aasovNPk85K44KiLdn3EW3QdCxobC2VIjOYnxvaDC/SxCtHpZ270CpCYttvmJjh44CBeqgcvh/PM9aiMqt8XAx9H4ks0lYiWBTwGfulADKt+ThfKjYw+WNzjr7Oz7xafiwuj6+m1E1W7vx430BJ+lgaVAoTq6UjtC/dkqi+fdBT0HyqKWsTfnfwl/DBQGECgYEA/BSUM9auxNlUME7OIMRn+1GD+go9I72AgZZm0zjm7NVFscdkxgRmAhU/GYpCncRNGwX+B9aRzrLDumgGM7QTHKxjaUp5aezucrCpxpihpDkL87jL4b9wog091/VOVWiBMXhNnREVIHlqaUEYpUQC0AeWv0oeXt+XDWK5+wZni8cCgYEA54h1aX1kJPR6xX2sV8Kl8iobXtRBZLzx79zhKFahULMS8bgLe9mKxE38GlcWJrFIXgRGx1Lzf9jmw5MD0s8FrqGTg8U391qzh2Hk3kZSkbiu7NPi2WKuAfbmYnuh41yUMlBWWIT/K7lIm+Bc/7RURp1QgHlQx+kwNVONhsQZSRECgYBVBjfquDmgqdEsrhf2k2ijKx6BwtxWZr+mde1exy2UqmbkjOWfqLIjd7kdyzWm8yQyvjWtvSDXABLml9mnrNBZdofdZsJHCSRwSMgq9SZoNtmiLi2OijzaW+8FHXd7dVFGN1auaKmgl3Nd5xgB/kuYkUa2ZLCTvYS8fhVO5x0b1wKBgAc0GKsSiqYXsSYp1c3ZMX6KTtWxduNieYiD78FoiJZRK/q3RiwxRX78CibrpLXJeD3sliMncon8vplBHrJVXJDlWAiWfzpD6SgCJLPBrln4TAD0Sq+GwXEwNFTGEfBX9ghmtXkFkkbS+e5Xma0e+CxGQrXskFXX7HcMRW/28+5xAoGBAO0XScQAVC09GdG8ElxiGdZtL4UvcurODPHUEMME4sxTbyx9iXBMXg6G7zX3eHkXO3SEBRY8JeO4f5G9VBuoFsXFB5bnQCzsytqG2MeUP5HuJyZl2fLDhWuuF8J7kTKA6rNw7DdcA+C25gy+MdLH5xu1l4smgvrSPeCowdJHj/Jj
          port: 22
          script: |
           cd /var/www/myapp/cicd/cicd
           git reset --hard git
           pull origin feature/jaydeep
           npm install 
           npm run build
           pm2 restart 0
           pm2 save
